SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Profile.Cache].[Concept.Mesh.URL](
	[DescriptorName] [varchar](255) NOT NULL,
	[NodeID] [bigint] NULL,
	[DescriptorUI] [varchar](10) NOT NULL,
	[URL] [varchar](553) NULL,
	[DefaultApplication] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[DescriptorName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

